server:
  port: 10012
logging:
  level:
    com.inhe.client: debug
    com.inhe.asset.service: debug
  file: logs/${spring.application.name}.log
  
mybatis:
  mapper-locations: classpath:com/inhe/mdm/mapper/*.xml,classpath:com/inhe/node/mapper/*.xml
  type-aliases-package: com.inhe.model.mdm,com.inhe.model.admin
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   
spring:
  aop:
    auto: true 
  application:
    name: inhe-platform-mdm
  mvc:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
    white-list: /api/auth/*,/index.html*,/js/*,/css/*,/img/*,/loading/*,/avatar2.jpg,/map.html
  datasource:
    url: jdbc:mysql://192.168.2.240:3306/cloud_mdm?useUnicode=true&amp;characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: root
    password: inhe@2011
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    timeZone: GMT+8 
    dbcp2:
      min-idle: 5                         #数据库连接池最小维持连接数
      initial-size: 5                     #初始化
      max-total: 30                       #最大连接数
      max-wait-millis: 200                #等待链接获取的最大超时时
  devtools:
    restart:
      enabled: false
  redis:
    database: 0  
    host: 192.168.2.239
    port: 6379
    timeout: 10000
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    leaseRenewalIntervalInSeconds: 5      #心跳间隔，5秒
    leaseExpirationDurationInSeconds: 10  #没有心跳的淘汰时间，10秒
  client:
    service-url:
      defaultZone: http://192.168.2.239:6001/eureka
    register-with-eureka: true
    registryFetchIntervalSeconds: 5       #定时刷新本地缓存时间  
ribbon:
  ServerListRefreshInterval: 2000         #ribbon缓存时间
endpoints:
  shutdown:
    enabled: true
    sensitive: true
  restart:
    enabled: true
management:
  security:
    enabled: false
feign: 
  hystrix: 
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
rocketmq:
  namesrvUrl: 192.168.2.239:9876
  producer:
    maxSize: 131072
    timeout: 10000
    retimes: 3
inhe:
  platformClient:
    svrUrl: http://INHE-PLATFORM-ADMIN
    pwd: 95f14e528e778fd3e0854a343266a64e7695fbcd45ecc347a68bf54018a87244
minio: 
  endpoint: http://192.168.2.239:9000
  accesskey: root
  secretkey: inhe1234