export default {
    exception: {
        msg3: 'Sorry, something went wrong with the server',
        msg2: 'Sorry, the function you visited is still developing',
        msg1: 'You have no permission to visit this function',
        btn1: 'Return Home',
    },
    footer: {
        tips1: 'Energy Home',
        tips2: 'INHEMETER Co,. LTD.',
    },
    steal: {
        theme04: 'Abnormal voltage and current diagnosis',
        theme03: 'Common power consumption diagnosis',
        theme06: 'Abnormal file diagnosis',
        theme05: 'Abnormal load diagnosis',
        theme02: 'Abnormal wiring diagnosis',
        theme01: 'Abnormal consumption diagnosis',
        drule0102: 'Monthly frozen data is the same with last month',
        drule0101: 'Monthly Frozen data is smaller than last month',
        drule0304: 'Power factor exceeding upper limit occurred',
        drule0303: 'Monthly electricity consumption drops or soars',
        drule0501: 'Phase power factor exceeding the lower limit event occurred',
        drule0302: 'Detected magnetic interference',
        drule0301: 'Terminal block cover or upper cover opening occurred',
        rule0201: 'Reverse consumption',
        rule0301: 'Meter cover opens',
        rule0302: 'Constant magnetic field interference',
        rule0303: 'Abnormal power consumption',
        rule0501: 'Continuous exceeds lower limit of load',
        pcontent: 'Processing content',
        rule0304: 'Abnormal power factor',
        drule0407: 'Unbalanced current event occurred',
        drule0406: 'Loss of current occurred',
        drule0405: 'Abnormal Phase B occurred in the meters with high voltage supply and metering',
        drule0603: 'Under the same branch, the user name is the same',
        drule0602: 'Meter change is recorded',
        drule0201: 'Current and power reverse occurred',
        index3: 'Anti-Stealing Rule',
        index2: 'Theme Code',
        index5: 'Factor',
        ptype: 'Process Type',
        index4: 'Rule description',
        drule0403: 'Unbalanced voltage occurred',
        drule0601: 'The meter status is inactivated',
        drule0402: 'Event of up over pre-defined rate voltage',
        drule0401: 'Event of phase missing',
        rule0101: 'Reverse power consumption',
        rule0102: 'Measurements interrupted',
        event: 'Electricity theft',
        factor: 'Suspicion',
        showtype2: 'By Event',
        showtype1: 'By Device',
        rule0401: 'Detected phase missing',
        rule0402: 'Voltage over phase',
        rule0403: 'Unbalanced voltage',
        rule0601: 'Inactivated status',
        rule0602: 'Meter change',
        rule0405: 'Abnormal phase B of meters with high voltage supply and metering',
        rule0603: 'Duplicated customer account',
        index1: 'Electricity stealing theme',
        rule0406: 'Loss of current event',
        rule0407: 'Unbalanced current',
        ptype0: 'System Failure',
        chart: 'Power consumption curve',
        ptype1: 'User Troubleshooting',
    },
    line: {
        code: 'Line Code',
        code1: 'Bus Code',
        cross: 'Cross Regional Mark',
        sort: 'Line category',
        type: 'Line type',
        add_btn: 'Add Line',
        placeholder1: 'Please select a substation',
        info1: 'Associated Substation',
        name: 'Line Name',
        placeholder: 'Please input the line code or name',
        parent_null: 'Substation can not be empty!',
        add_btn1: 'Import',
        name1: 'Bus Name',
    },
    transformer: {
        date: 'Commissioning date',
        code: 'Transformer Code',
        title1: 'Select Line',
        type: 'Transformer Type',
        add_btn: 'Add Transformer',
        placeholder1: 'Please select a line',
        info1: 'Associated Line',
        name: 'Transformer Name',
        placeholder: 'Please input the transformer code or name',
        parent_null: 'Substation can not be empty!',
        add_btn1: 'Import',
        info3: 'Capacity(kVA)',
        info2: 'Associated Department',
    },
    login: {
        placeholder3: 'Account or Mail Address',
        placeholder4: 'Verification Code',
        placeholder5: 'Account or Mail Address',
        title: 'Welcome to use the INHE Energy Cloud',
        msg4: 'Welcome',
        msg3: 'Your Verification Code is',
        msg2: 'Information',
        msg1: 'The  verification code is sending',
        msg5: 'Wecome Back',
        mobile: 'Mobile or Mail Address',
        tips4: 'Please enter the Verification Code',
        tips5: 'No Account?',
        title1: 'Login By Password',
        tips6: 'Register Now',
        title2: 'Login By Code',
        title3: 'Operator',
        title4: 'Password',
        tips1: 'Please enter  the account name or email address',
        title5: 'Login By Password',
        tips2: 'Please enter your password',
        tips3: 'Please enter the correct phone number',
        btn6: 'Register',
        btn4: 'Get Verification Code',
        placeholder1: 'Account , Mail Address or Mobile Number',
        btn5: 'Login',
        placeholder2: 'Password',
        btn2: 'Register',
        btn3: 'Confirm',
        btn1: 'Auto-Login',
    },
    web_client: {
        HEAD_TITLE: 'STS',
        MENU_TITLE: 'STS',
        FOOT_TITLE: 'STS',
    },
    button: {
        _006_msg1: 'Information',
        _011_msg1: 'Information',
        _006_msg2: 'Are you sure you want to enable the selected record?',
        _011_msg2: 'Are you sure you want to send the selected record?',
        _006_msg3: 'Are you sure you want to disable the selected record?',
        _009_msg2: 'Are you sure you want to print the selected record?',
        _009_msg1: 'Information',
        _008_msg1: 'Information',
        _008_msg2: 'Are you sure you want to export the selected record?',
        _009: 'Print',
        _008: 'Export',
        _007: 'Import',
        _002: 'Add',
        _001: 'Search',
        _006: 'Enable/Disable',
        _005: 'Details',
        _004: 'Delete',
        _003: 'Edit',
        _001_placeholder: 'Please enter the query content',
        _004_msg1: 'Information',
        _004_msg2: 'Are you sure you want to delete the selected record?',
        _006_off: 'Disable',
        _006_on: 'Enable',
        _011: 'Sending',
        _010: 'Reset Password',
    },
    loss: {
        bus: 'Bus Equilibrium',
        select: 'Select metering point',
        dire0: 'Supply in',
        dire1: 'Supply out',
        supkwh: 'kWh Supply(kWh)',
        supply: 'Type of power supply',
        selected: 'Selected metering point',
        add: 'Batch generation',
        par: 'Percent',
        buscode: 'Bus Code',
        tmname: 'Transformer Area Name',
        edit: 'Modify Quota',
        info6: 'Line Loss Rate(%)',
        addtype0: 'Artificial modeling',
        info1: 'Year-On-Year(%)',
        info5: 'Line Loss Range(%)',
        info4: 'Quota(%)',
        info3: 'Loss Rate(%)',
        info2: 'Month-On-Month(%)',
        report2: 'Feeder Report',
        decount: 'Device Qty.',
        report3: 'Public Transformer Report',
        report0: 'Partition Report',
        report1: 'Divided Voltage Report',
        tmcode: 'Transformer Area Code',
        index3: 'Metering point of supply and output',
        index2: 'Supply metering point',
        index5: 'Supply in count',
        index4: 'Supply out count',
        index7: 'Monthly Line Loss Quota(%)',
        year1: 'Annual Cumulative kWh Supply(kWh)',
        delete: 'Bulk delete',
        index6: 'Daily Line Loss Quota(%)',
        year2: 'Annual Cumulative kWh Sold(kWh)',
        index9: 'Build date',
        year3: 'Annual Cumulative kWh Loss(kWh)',
        index8: 'Generated or not',
        year4: 'Annual Cumulative Loss Rate(%)',
        rate: 'Line Loss Range(%)',
        mdire0: 'Forward',
        busname: 'Bus Name',
        mdire1: 'Reverse',
        soldkwh: 'kWh Sold(kWh)',
        model3: 'Public Transformer Model',
        model2: 'Feeder Model',
        model1: 'Divided Voltage Model',
        losskwh: 'Loss kWh(kWh)',
        model0: 'Partition Model',
        ana1: 'Branch Line Loss Condition',
        ana2: 'Line Loss Condition By Transformer Area',
        index1: 'Generation way',
        action1: 'Build model',
        action2: 'Add measurement point',
        action3: 'Delete model',
    },
    common: {
        date: 'Date',
        btn_cancel1: 'Cancel',
        select: 'Select',
        btn_refresh: 'Refresh',
        errorCode: 'Error Code',
        import_alert: 'null',
        import_info1: 'Details of Imports : {total} records were found, of which {success} records were successfully imported and {fail} records failed to be imported',
        lvmeter: 'LV Meter',
        vol_level: 'Voltage Level',
        import_info7: 'Please upload the XLSX file',
        btn_reset: 'Reset',
        longitude: 'Longitude',
        btn_search: 'Search',
        btn_fold: 'Close',
        import_xlsx: 'Select one XLSX file',
        btn_confirm: 'Confirm',
        btn_edit: 'Edit',
        verify_code: 'Verification Code',
        btn_sure: 'Confirm',
        process1: 'Processed',
        download_model: 'The format of file',
        notnull: 'can not be empty!',
        process0: 'Unprocessed',
        mainmeter: 'Master Meter',
        select_title3: 'Select  Meter',
        select_title4: 'Select  Device',
        select_title1: 'Select  Substation',
        detail: 'Detail',
        recount: 'Recount',
        select_title2: 'Select  Transformer',
        fail_reason: 'Fail reason',
        status: 'Status',
        no: 'No',
        latitude: 'Latitude',
        btn_ok: 'Submit',
        btn_sctead: 'Open',
        selectone: 'Please select an item first',
        import_csv: 'Select one CSV file',
        msg2: 'Import successfully',
        process: 'Process',
        selectmain: 'Select Main Substation',
        address: 'Address',
        msg1: 'Upload failed',
        yes: 'Yes',
        stepok: 'Complete',
        step1: 'Step1',
        btn_more: 'More',
        btn_cancel: 'Return',
        location: 'Location',
        time: 'Time',
    },
    dct: {
        DEVICE_STATUS0: 'Running',
        DEVICE_STATUS1: 'Stopped',
        LINE_SORT1: 'Busbar',
        DEVICE_STATUS2: 'Removed',
        FUN_LAYOUTBlankLayout: 'Blank Layout',
        LINE_SORT0: 'Feeder',
        TASK_ACTIVEDY: 'Enable',
        TASK_ACTIVEDN: 'Disable',
        FUN_LAYOUTRouteView: 'Route View',
        FUN_STATUS0: 'Enable',
        FUN_STATUS1: 'Disable',
        REPEAT_TYPE4: 'Month',
        REPEAT_TYPE5: 'Year',
        REPEAT_TYPE2: 'Hour',
        REPEAT_TYPE3: 'Day',
        REPEAT_TYPE0: 'Second',
        REPEAT_TYPE1: 'Minute',
        FUN_PUBLICY: 'Public',
        TASK_TYPE1: 'Service',
        TASK_TYPE0: 'Task',
        METER_SORT0: 'Feeder',
        METER_SORT1: 'Private Transformer',
        METER_SORT2: 'Transformer Area',
        METER_SORT3: 'Low voltage',
        FUN_PUBLICN: 'Private',
        LINE_TYPE0: 'Public Line',
        LINE_TYPE1: 'Private Line',
        METER_SORT4: 'Substation',
        FUN_LAYOUTBasicLayout: 'Basic Layout',
        METER_SORT5: 'Resident user',
        METER_SORT6: 'Total meter',
        METER_SORT7: 'Busbar',
        TASK_PLAN_STATUS0: 'Executing',
        TASK_PLAN_STATUS1: 'Execution complete',
        TASK_EXECINGN: 'No',
        FUN_LAYOUTUserLayout: 'Login page layout',
        MEAS_MODE0: 'High - High Metering',
        VOL_LEVEL0: '220V',
        MEAS_MODE1: 'High - Low Metering',
        VOL_LEVEL1: '380V',
        MEAS_MODE2: 'Low - Low Metering',
        VOL_LEVEL2: '10kV',
        VOL_LEVEL3: '35kV',
        VOL_LEVEL4: '110kV',
        VOL_LEVEL5: '220kV',
        VOL_LEVEL6: '500kV',
        TASK_EXECINGY: 'Yes',
        TM_TYPE0: 'Private Transformer',
        FUN_LAYOUTPageView: 'Breadcrumbs',
        TM_TYPE1: 'Public Transformer',
        TM_TYPE2: 'Shared Private Transformer',
    },
    param: {
        remark_placeholder: 'Please enter the remarks',
        code: 'Code',
        description_placeholder: 'Please enter the description',
        description: 'Description',
        remark: 'Remarks',
        v1_placeholder: 'Please enter the Property 1',
        title: 'Details',
        type: 'Type',
        tips1: 'Please upload the image format',
        btn_ok: 'Submit',
        tips2: 'The size of picture cannot be greater than 2Mb',
        tips3: 'Submitted Successfully',
        type_placeholder: 'please select the type of parameters',
        code_placeholder: 'Please enter the code',
        v2_placeholder: 'Please enter the Property 2',
        tip: 'The file must be JPG, GIF, or PNG and less than 60px in size',
        v1: 'Property 1',
        v3_placeholder: 'Please enter the Property 3',
        v2: 'Property 2',
        v3: 'Property 3',
        v4: 'Property 4',
        v4_placeholder: 'Please enter the Property 4',
    },
    function: {
        _13: 'Menu',
        _35: 'Line Loss Model',
        _34: 'Line Loss Management',
        _15: 'Grid Management',
        _37: 'Main Network Loss',
        _14: 'Opeartor Log',
        _36: 'Four-Ins Line Loss',
        _17: 'Substation',
        _39: 'Line Loss Report',
        _16: 'Grid structure',
        _38: 'Line Loss Analysis',
        _19: 'Line',
        _18: 'Main Substation',
        _40: 'Four-Ins Line Loss Report',
        _20: 'Transformer',
        _41: 'Main Network Loss Report',
        _22: 'Distribution Grid Device',
        _21: 'Main Grid Device',
        _24: 'VEE Configuration',
        _23: 'VEE Management',
        _26: 'VEE Log',
        _25: 'Edit Data',
        _28: 'Electricity stealing theme',
        _27: 'Anti stealing management',
        _29: 'Electricity stealing analysis',
        _root: 'Home',
        _1: 'Dashboard',
        _2: 'Dashboard',
        _3: 'Platform',
        _4: 'Parameters',
        _5: 'Dictionary',
        _6: 'Internationalization',
        _31: 'Consumption Analysis',
        _30: 'Application Analysis',
        _33: 'Power Structure Analysis',
        _32: 'Power Ranking Analysis',
    },
    sparm: {
        WEB_CLIENT_FOOT_TITLE: 'Bottom description',
        WEB_CLIENT_HEAD_TITLE: 'Page title',
        WEB_CLIENT_HEAD_ICON: 'Web icon',
        CLASSES_WEB_CLIENT: 'Interface',
        WEB_CLIENT_MENU_TITLE: 'Menu title',
    },
    substation: {
        add_btn: 'Add Substation',
        code: 'Substation Code',
        name_null: 'Substation name can not be empty!',
        name: 'Substation Name',
        placeholder: 'Please input the substation code or name',
        add_btn1: 'Import',
    },
    vee: {
        R001_L: 'The value is less than last value',
        R006_L2: 'Coefficient',
        R006_L1: 'Number of average values',
        R003_L: 'No value for N times continuously',
        f_index2: 'Command Name',
        f_index1: 'OBIS Code/Field ID',
        E001_L1: 'Times',
        f_index3: 'Unit',
        obis: 'Command Id.',
        R016_L1: 'Far less than (coefficient)',
        R016_L2: 'Far greater than (a coefficient)',
        R005_L: 'The value is zero',
        R009_L2: 'Multiple',
        R007_L: 'Consumption is much lower than average（average）',
        R009_L1: 'Constant',
        R009_L: 'Consumption is much higher than average（constant）',
        ftype09: 'Daily electricity consumption',
        ftype08: 'Real time reading',
        R011_L: 'The data is negative number',
        R013_L: 'Sum check: Sum of daily consumption compared with monthly consumption',
        R007_L2: 'Coefficient',
        R003_L1: 'Times',
        R015_L: 'Consumption compared with the same month of last year',
        title1: 'Select a validation device',
        title2: 'Select Field',
        ftype07: 'Instantaneous data',
        ftype06: 'Curve data',
        ftype05: 'billing data',
        add_btn: 'Add VEE configuration',
        ftype10: 'Monthly electricity consumption',
        R017_L1: 'Far less than (coefficient)',
        R017_L2: 'Far greater than (a coefficient)',
        rule_detail1: 'Alarm mode',
        files: 'Commands',
        R017_L: 'Maximum demand compared with the same month of last year',
        rule_detail0: 'Whether to continue after failed verification',
        rule_detail2: 'ignore',
        R002_L: 'The value equals to last value',
        R004_L2: 'Maximum value',
        R004_L: 'The value exceeds the preset range',
        R004_L1: 'Minimum value',
        index3: 'Fields Qty.',
        rule1: 'Validation rules',
        index2: 'Rules Qty.',
        ftype12: 'Monthly meter reading success rate',
        index5: 'Activate',
        ftype11: 'Daily meter reading success rate',
        index4: 'Operator',
        rule2: 'Estimate rules',
        R014_L1: 'Far less than (coefficient)',
        datatype: 'Data Type',
        R010_L1: 'Times',
        R014_L2: 'Far greater than (a coefficient)',
        R006_L: 'Consumption is much lower than average（average）',
        R007_L1: 'Constant',
        placeholder: 'Please input task name',
        R008_L: 'Consumption is much higher than average（average）',
        value: 'Value',
        E001_L: 'Take N times average',
        R010_L: 'The data is zero for N times continuously',
        R012_L: 'Sum check: Time of use compared with total use',
        R014_L: 'Consumption compared with the last month',
        R015_L2: 'Far greater than (a coefficient)',
        R015_L1: 'Far less than (coefficient)',
        filescount: 'Selected Fields',
        index1: 'Task Name',
        index0: 'Task Code',
        R008_L1: 'Number of average values',
        R016_L: 'Maximum demand compared with the last month',
        R008_L2: 'Multiple',
        kwh: 'Consumption(kWh)',
    },
    dict: {
        remark_placeholder: 'Please enter the remarks info',
        code: 'Code',
        pbl_select: 'Please select a record',
        description_placeholder: 'Please enter the description',
        description: 'Description',
        remark: 'Remarks',
        v1_placeholder: 'Please enter the Property 1',
        title: 'Detials',
        type: 'Type',
        type_placeholder: 'Please select one type',
        code_placeholder: 'Please enter the completed code',
        v2_placeholder: 'Please enter the Property 2',
        action: 'Action',
        v1: 'Property 1',
        v3_placeholder: 'Please enter the Property 3',
        v2: 'Property 2',
        v3: 'Property 3',
        v4: 'Property 4',
        v4_placeholder: 'Please enter the Property 4',
    },
    lock: {
        title: 'The system has been locked, please enter the password to unlock!',
        btn: 'Unlock',
    },
    maintransformer: {
        add_btn: 'Add Main transformer',
        code: 'Main transformer Code',
        name_null: 'Main transformer name can not be empty!',
        placeholder1: 'Please select a substation',
        info1: 'Associated Substation',
        name: 'Main transformer Name',
        placeholder: 'Please input the main transformer code or name',
        parent_null: 'Substation can not be empty!',
        add_btn1: 'Import',
    },
    power: {
        index10: 'Public Line Private Transformer Consumptionn',
        index1: 'Ranking',
        index11: 'Public Line Public Transformer Consumption',
        index3: 'End Value',
        index2: 'Total kWh',
        index5: 'Year-On-Year(%)',
        index4: 'Start Value',
        index7: 'Important Device',
        index6: 'Month-On-Month(%)',
        index9: 'Private Line Private Transformer Consumption',
        index8: 'Change meter power',
    },
    lang: {
        content_placeholder: 'Please enter the content',
        msg2: 'null',
        msg1: 'Submitted successfully',
        index: '',
        title1: 'Add Language',
        content: 'Content',
        id_placeholder: 'Please enter the keyword 2',
        lang_type_placeholder: 'Please enter the keyword 1',
        action: 'Action',
        lang_type: 'Keyword 1',
        lang3: 'Language 3',
        tip: 'Importing the language file',
        id: 'Keyword 2',
        lang2: 'Language 2',
        lang1: 'Language 1',
    },
    welcome: {
        msg4: 'Good Afternoon',
        msg3: 'Good Afternoon',
        msg2: 'Good Morning',
        msg1: 'Good Morning',
        msg5: 'Good Evening',
    },
    dataedit: {
        date: 'Data time',
        index3: 'Estimated Value',
        device_num: 'Device Num',
        index2: 'Read Value',
        index5: 'Pre-edit Value',
        index4: 'Edited Value',
        index7: 'Contract No.',
        station_placeholder: 'Please enter the code of substation',
        index6: 'Set Value',
        index9: 'Rule Code',
        index8: 'Meter No.',
        maintrans_placeholder: 'Please enter the code of main substation',
        index41: 'Edited Value',
        index10: 'Result',
        index11: 'Remarks',
        title1: 'Edit Data',
        result_type0: 'Validation Failed',
        result_type1: 'Unable Verification',
        result_type2: 'Estimation Failed',
        line_placeholder: 'Please enter the code of line',
        result_type3: 'Estimate Successed',
        tm_placeholder: 'Please enter the code of transform',
        device_num_placeholder: 'Please enter the number of device',
        index1: 'Type',
        result_type4: 'Edited',
    },
    table: {
        tips4: 'Totals',
        tips5: 'records',
        tips1: 'Selected',
        tips2: 'Totals',
        tips3: 'Empty',
    },
    info: {
        db_version: 'Database Version',
        app_pom_time: 'The last time of POM upgrated',
        db_upgrate_time: 'Database Upgrated Time',
        app_version: 'App Version',
        app_build_time: 'App Packaging Time',
        company: 'INHEMETER',
        version_info: 'Version Information',
        copy_right: 'Copyright @2020 All Rights Reserved',
    },
    err: {
        -108011: 'Transformer already exists',
        -108001: 'Cannot find the specified substation',
        -108012: 'Cannot find the specified measuring point',
        -108002: 'The designated substation is deleted',
        -108013: 'The metering point already exists',
        -108003: 'Please select a file with the suffix xlsx or xls',
        -108014: 'The specified transformer is deleted',
        -108201: 'The record you selected has an ungenerated line loss model',
        -108010: 'Cannot find the specified transformer',
        -108008: 'Cannot find the specified line',
        -108009: 'Line already exists',
        -108004: 'File content format error',
        -108015: 'Wrong department number generated (non-numeric characters may be present)',
        -108005: 'The substation already exists',
        -108016: 'The device is not under the department of substation or transformer',
        -108006: 'Cannot find the main transformer',
        -108007: 'The main transformer already exists',
    },
    org: {
        select_org: 'please select one organization',
        user_name: 'Operator',
        select_msg1: 'Please select a record',
        mobile: 'Mobile',
        org_name: 'Name',
    },
    meter: {
        index1: 'Metering Point Name',
        index3: 'Host Transformer',
        index2: 'Metering Point Type',
        index5: 'Date of Operation',
        index4: 'Important Mark',
    },
    drawer: {
        menu_type1: 'Dark',
        tabs_item12: 'Streaming',
        tabs_item11: 'Fixed',
        title1: 'Style',
        title2: 'Theme Color',
        title3: 'Navigation Mode',
        title4: 'Others Setting',
        tips1: 'null',
        tabs_item5: 'Color Blindness Mode',
        tips2: 'null',
        menu_type2: 'Bright',
        tabs_item4: 'Fixed the side menu',
        tabs_item3: 'Hide Header',
        tabs_item2: 'Fixed Head',
        tabs_item1: 'Content Block',
        tabs_type1: 'Sidebar Navigation',
        tabs_type2: 'Top Navigation',
    },
    index: {
        foot_title2: 'null',
        foot_title1: 'INHEMETER Co,. LTD.',
        foot_title4: 'null',
        foot_title3: 'null',
        content_title1: 'null',
        title_bottom2: 'null',
        title_second: 'null',
        content_item5: 'null',
        content_item6: 'null',
        content_item7: 'null',
        content_item8: 'null',
        content_item1: 'Billing',
        content_item2: 'Meter Reading, Remote Control',
        content_item3: 'null',
        title_top: 'null',
        content_item4: 'null',
        login_title: 'null',
        content_item12: 'APP, Wechat',
        content_item11: 'Mobile Payment, SMS Reminder',
        content_item10: 'Mobile App',
        content_item9: 'null',
        content_title6: 'null',
        content_title10: 'null',
        content_title7: 'null',
        content_title11: 'null',
        content_title8: 'null',
        title_bottom1: 'null',
        content_title12: 'null',
        content_title9: 'null',
        content_title2: 'null',
        content_title3: 'null',
        content_title4: 'null',
        content_title5: 'null',
    },
    user_menu: {
        item2: 'Account Settings',
        msg2: 'Do you really want to log out?',
        item1: 'Personal center',
        msg1: 'Information',
        item3: 'Log out',
    },
    dept: {
        index_null: 'Department can not be empty!',
        tree_placeholder: 'Please select the department',
        index: 'Department',
    },
    analysis: {
        type: 'By Line',
    },
    step2: {
        btn2: 'Go ahead',
        tips4: 'Wait for a moment',
        btn3: 'Lost Phone?',
        tips5: 'please entering the verification code',
        btn1: 'Return',
        title: 'Two Steps',
        tips1: 'null',
        tips2: 'Input check code',
        tips3: 'Verifying',
    },
    user_layou: {
        item2: 'Privacy',
        item1: 'Helper',
        item3: 'Terms',
        tips1: 'null',
        tips2: 'Copyright © INHEMETER Co,. LTD.',
    },
    task: {
        card1: '',
        description_msg1: '',
        plan_cdate: 'Creation time',
        plan_params: '',
        plan_code: '',
        type: '',
        task_name_placeholder: 'null',
        plan_exectime: '',
        next_time: '',
        base_time_msg1: 'null',
        record_stime: '',
        action: 'Action',
        tip: 'null',
        edit_card: 'null',
        ws_id: '',
        params_placeholder: '',
        work_cycle: 'null',
        task_plan_list: 'null',
        cycle_type_msg1: '',
        task_code: 'null',
        description_placeholder: '',
        params: '',
        code_msg1: '',
        record_result: '',
        fail: 'null',
        record_sn: '',
        plan_detail: 'null',
        add_task: 'null',
        cycle_msg1: '',
        success: 'null',
        ws_id_placeholder: '',
        plan_list: '',
        plan_status: '',
        base_time: '',
        task_name: 'null',
        code: '',
        record_etime: '',
        type_msg1: '',
        description: 'Description',
        cycle_type: '',
        record_remark: '',
        cycle: '',
        cycle_placeholder: '',
        record_list: '',
        edit_work_id: 'null',
        code_placeholder: '',
        sn: '',
        plan_datatime: '',
        close: 'null',
        actived: 'Status',
        work_id: 'null',
        ws_id_msg1: '',
        next_time_msg1: 'null',
        plan_msg2: '',
        plan_msg1: '',
        plan_reset: '',
        index1: '#',
    },
    veelog: {
        type2: 'Edited',
        index1: 'VEE Type',
        index3: 'Customer Name',
        result0: 'Passed',
        index2: 'Customer No.',
        type1: 'Estimate',
        type0: 'Validate',
        result2: 'Failed',
        result1: 'Not passed',
    },
    register_succ: {
        btn2: 'Return Home',
        btn1: 'Check Mail',
        tips1: 'Registered successfully, you can use this account to experience the system!',
        tips2: 'Your account',
        tips3: 'Registered successfully',
    },
    device: {
        add_btn: 'Add Device',
        placeho: 'Please enter the number of device',
        index1: 'Device No.',
        dire: 'Measurement direction',
        index3: 'Installation Address',
        index2: 'Device Name',
        title1: 'Metering Point Info',
        index5: 'Metering Mode',
        title2: 'Meter Information',
        index4: 'Meter sort',
        placeholder: 'Please input the device number,name or address',
    },
    kwh: {
        normal: 'Normal',
        status1: 'The kWh is too large',
        data4: 'Average(T4)',
        data3: 'Off- Peak(T3)',
        data2: 'Shoulder (T2)',
        data1: 'Peak(T1)',
        status2: 'The kWh is too low',
        type1: 'Monthly kWh',
        kwh: 'Consumption(kWh)',
        status3: 'The kWh is zero',
        type0: 'Daily kWh',
    },
    mainnetwork: {
        address: 'Installation Address',
    },
    fun: {
        image: 'Icon',
        image_placeholder: 'Refer to https://www.antdv.com/components/icon-cn/',
        msg1: 'The action may cause serious consequences, please be careful!',
        url_placeholder: 'Please enter the URL',
        fun_name_placeholder: 'Please enter the name of menu',
        tree_title: 'Function list',
        is_public_msg1: 'The published information can not be empty',
        url: 'URL',
        layout: 'Layout',
        fun_name_msg1: 'The name of menu can not be empty',
        is_public: 'Public Information',
        action: 'Action',
        status_msg: 'The status of menu can not be empty',
        detail: 'Details of Menu',
        actions: 'Actions List',
        fun_name: 'Menu Name',
        status: 'Status',
    },
    register: {
        org_user_type1: 'Registered user',
        org_user_type2: 'Provider of Service',
        strength: 'Intensity',
        placeholder3: 'Confirm the password',
        placeholder4: 'User Code',
        placeholder5: 'Verification Code',
        placeholder6: 'Mobile',
        placeholder7: 'Verification Code',
        msg4: 'The  verification code is sending',
        org_user_type_msg1: 'The type can not be empty',
        msg3: 'The password is not same',
        msg2: 'Please enter your password',
        msg1: 'Weak Password',
        msg8: 'Get Verification Code',
        msg7: 'An error in the request. Please try again later',
        msg6: 'Your Verification Code is',
        msg5: 'Information',
        tips4: 'Please enter the user code',
        tips5: 'Please enter the Verification Code',
        title1: 'Register',
        tips6: 'Please enter the correct phone number',
        strength0: 'Very weak',
        tips1: 'Please enter the correct email format',
        tips2: 'Please enter at least 6 characters.Please include at least 2 Numbers, letters and special characters.',
        tips3: 'Passwords with at least 6 characters, case sensitive',
        strength1: 'weak',
        strength2: 'Middle',
        btn4: 'Login',
        placeholder1: 'Mail',
        strength3: 'Strong',
        placeholder2: 'Set Password',
        btn2: 'Register',
        btn3: 'null',
        btn1: 'Get Verification Code',
        org_user_type: 'Operator Type',
    },
}
